# Generated by Django 4.2.7 on 2026-09-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="adresse email"
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="nom complet")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Administrateur système", "Administrateur système"),
                            (
                                "Secrétariat général / Bureau du courrier",
                                "Secrétariat général / Bureau du courrier",
                            ),
                            (
                                "DGS / Secrétaire municipal",
                                "DGS / Secrétaire municipal",
                            ),
                            ("Chef de service municipal", "Chef de service municipal"),
                            ("Agent communal", "Agent communal"),
                        ],
                        default="Agent communal",
                        max_length=80,
                    ),
                ),
                ("service", models.CharField(max_length=255)),
                ("actif", models.BooleanField(default=True)),
                (
                    "avatar",
                    models.TextField(
                        blank=True, help_text="Data URL de la photo de profil"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
            },
        ),
    ]
