# Generated by Django 5.2.17 on 2026-09-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.FileField(
                blank=True, upload_to="avatars/", verbose_name="photo de profil"
            ),
        ),
    ]
