# Generated by Django 5.2.17 on 2026-09-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_services_et_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
