# Generated by Django 4.2.7 on 2026-09-20 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("Administration", "Administration"),
                            ("Association", "Association"),
                            ("Entreprise", "Entreprise"),
                            ("Élu", "Élu"),
                            ("Citoyen", "Citoyen"),
                        ],
                        max_length=32,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Courrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=32, unique=True)),
                (
                    "sens",
                    models.CharField(
                        choices=[("Arrivée", "Arrivée"), ("Départ", "Départ")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("tiers", models.CharField(max_length=255)),
                ("objet", models.TextField()),
                ("service", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=64, verbose_name="type / mode")),
                (
                    "priorite",
                    models.CharField(
                        choices=[("Normale", "Normale"), ("Urgente", "Urgente")],
                        max_length=10,
                    ),
                ),
                ("statut", models.CharField(max_length=64)),
                ("echeance", models.DateField()),
                ("responsable", models.CharField(max_length=255)),
                ("signataire", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "courrier",
                "verbose_name_plural": "courriers",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courrier_numero", models.CharField(blank=True, max_length=32)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("lue", models.BooleanField(default=False)),
                (
                    "courrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="courriers.courrier",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
