# Generated by Django 5.2.17 on 2026-09-28 13:41

import courriers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courriers", "0003_reprise_des_donnees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        storage=courriers.models.stockage_pieces, upload_to="%Y/%m/"
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="nom d'origine")),
                ("taille", models.PositiveIntegerField()),
                ("type_mime", models.CharField(blank=True, max_length=100)),
                ("ajoute_par_nom", models.CharField(blank=True, max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "ajoute_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "courrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="courriers.courrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "pièce jointe",
                "verbose_name_plural": "pièces jointes",
                "ordering": ["date", "id"],
            },
        ),
    ]
